// src/components/UI/Navbar.tsx
import React, { FC } from 'react';
import "bootstrap/dist/css/bootstrap.min.css";
import AppRouter from '../../app/Router';

const Navbar: FC = () => {
  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-primary px-4">
    <a className="navbar-brand" href="#">Navbar</a>
    <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div className="navbar-nav">
      <a className="nav-item nav-link active" href="#">Home <span className="sr-only">(current)</span></a>
      <a className="nav-item nav-link" href="#">Features</a>
      <a className="nav-item nav-link" href="#">Pricing</a>
      <a className="nav-item nav-link disabled" href="#">Disabled</a>
    </div>
  </div>
</nav>
  );
}

export default Navbar;

// admin-panel-angular/src/app/UI/navbar/navbar.component.ts
import { Component } from '@angular/core';    
    
@Component({    
    selector:'app-navbar',    
    templateUrl:'./navbar.component.html',    
    styleUrls:['./navbar.component.css']    
    })   
    
export class NavbarComponent    
{      
}    
<nav class="navbar navbar-expand-lg navbar-dark bg-primary px-4">
  <a class="navbar-brand" href="#">
    MOODME LOGO
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-a active" href="#">Home <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-a" href="/licenses">licenses</a>
      <a class="nav-item nav-a" href="#">Pricing</a>
      <a class="nav-item nav-a disabled" href="#">Disabled</a>
    </div>
  </div>
</nav>
