// src/components/licenses/addLicenseForm.tsx
import React, { useState } from "react";
import  { Link } from 'react-router-dom'
import { Formik, FormikHelpers, ErrorMessage, Field, Form} from "formik";
import * as Yup from "yup";
// import { CreateLicense } from "../services/license";
import image from "../../assets/moodme-logo.png"
import { CreateLicense } from '../../Models';


const AddLicenseForm = () => {
  const [message, setMessage] = useState("")

  const initialValues : CreateLicense = {
    productID: 0,
    appID: '',
    customerID: 0,
    expiresAt: 0,
  };

  const validationSchema = Yup.object().shape({
      productID: Yup.number()
        .required('Product is required'),
      appID: Yup.string().required('Application is required'),
  });

  const handleSubmit = (
    { productID, appID, customerID, expiresAt}: CreateLicense,
    { setSubmitting }: FormikHelpers<CreateLicense>
  ) => {
    try {
      // await CreateLicense({productID, appID, customerID, expiresAt});
      console.log({productID, appID, customerID, expiresAt})
      setMessage("Message from create licence")
    } catch(error) {
      setSubmitting(false);
      console.log(error)
    }
  }

  return (
    <Formik
      initialValues={initialValues}
      validationSchema={validationSchema}
      onSubmit={handleSubmit}
    >
      {({ errors, touched, isSubmitting}) => (
        <div className="col-md-12 ModalForm">
          <div className="card card-container">
            <h3>Create Licence</h3>
            <img
              src={image}
              alt="profile-img"
              className="profile-img-card"
            />
            <Form>
              <div className="form-group">
                <label htmlFor="productID">productID</label>
                <Field
                  className="form-control"
                  type="text"
                  name="productID"
                />
                <ErrorMessage
                  name="productID"
                  component="div"  
                  className="alert alert-danger"
                />
    
              </div>
              <div className="form-group">
                <label htmlFor="appID">appID</label>
                <Field
                  className="form-control"
                  type="text"
                  name="appID"
                />
                <ErrorMessage
                  name="appID"
                  component="div"
                  className="alert alert-danger"
                />
              </div>
              <div className="form-group">
                <label htmlFor="customerID">customerID</label>
                <Field
                  className="form-control"
                  type="text"
                  name="customerID"
                />
                <ErrorMessage
                  name="customerID"
                  component="div"
                  className="alert alert-danger"
                />
              </div>
              <div className="form-group my-4" >
                <button
                  type="submit"
                  className="btn btn-primary btn-block"
                  disabled={
                    isSubmitting ||
                    (!!errors.productID && touched.productID) ||
                    (!!errors.appID && touched.appID) ||
                    (!!errors.customerID && touched.customerID)
                  }
                >
                  {isSubmitting && (
                    <span className="spinner-border spinner-border-sm"></span>
                  )}
                  <span>Create Licence</span>
                </button>
              </div>
              {message && (
                <div className="form-group my-4">
                  <div className="alert alert-danger" role="alert">
                    {message}
                  </div>
                </div>
              )}
            </Form>
            <Link to="/">
              Know more about licenses?
            </Link>
          </div>
        </div>
      )}
    </Formik>
  )
}

export default AddLicenseForm;

// admin-panel-angular/src/app/license/AddLicenseForm/AddLicenseForm.component.ts
import { Component, Injectable, OnInit } from '@angular/core';
import { CognitoService } from 'cognito-angular';
import { Router } from '@angular/router';
import * as API from '../../../api/licenseService';

import { CreateLicenseInput, LicenseInfo } from '../../../api/licenseService';

const licenseAPI = new API.LicensingApi


@Component({
  selector: 'add-license-form',
  templateUrl: './AddLicenseForm.component.html',
  styleUrls: ['./AddLicenseForm.component.css'],
})

@Injectable()

export class AddLicenseForm implements OnInit {

    productID: number;
    appID: string;
    customerID: number;
    expiresAt: number;

  constructor(private LicensingApi: API.LicensingApi, private router: Router) {
    this.productID = 1;
    this.appID = '';
    this.customerID = 0;
    this.expiresAt = 0;
  }
  ngOnInit(): void {}

  async onSubmit() {
    try {
      const body: CreateLicenseInput = {
        productID: this.productID,
        appID: this.appID,
        customerID: this.customerID,
        expiresAt: this.expiresAt,
      }
      console.log(body)
      await this.LicensingApi.createLicense(body);
      this.router.navigate(['license']);
    } catch (error) {
      console.log(error)
    }    
  }
}
<div class="container text-center d-flex justify-content-center">
<div class="col-md-6 ModalForm center">
  <div class="card card-container p-4 my-4">
    <h3>Create Licence</h3>
    <!-- <img
      src={image}
      alt="profile-img"
      class="profile-img-card"
    /> -->
    <Form>
      <div class="form-group">
        <label htmlFor="appID">appID</label>
        <input
          class="form-control"
          type="text"
          name="appID"
          [(ngModel)]="appID"
        />
      </div>
      <div class="form-group">
        <label htmlFor="customerID">customerID</label>
        <input
          class="form-control"
          type="text"
          name="customerID"
          [(ngModel)]="customerID"
        />
      </div>
      <div class="form-group my-4" >
        <button
          type="button"
          class="btn btn-primary btn-block"
          (click)="onSubmit()"
        >
          <span>Create Licence</span>
        </button>
      </div>
    </Form>
    <a to="/">
      Know more about licenses?
    </a>
    <button
      routerLink="/license"
      type='button'
      class="btn btn-primary mx-1"
    >
      Licenses list
    </button>
  </div>
</div>
</div>
